on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0  # Ensure .NET 8 is available
          2.1  # .NET Core 2.1 includes .NET Standard 2.0

    - name: Restore dependencies
      run: dotnet restore GermanToCSharpKeywordsGenerator.sln

    - name: Build
      run: dotnet build GermanToCSharpKeywordsGenerator.sln --configuration Release

    - name: Run Unit Tests
      run: dotnet test GermanToCSharpKeywordsGenerator.Unittests/GermanToCSharpKeywordsGenerator.Unittests.csproj --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"

    - name: Generate MSBuild Logs (for Debugging)
      if: failure()
      run: dotnet msbuild GermanToCSharpKeywordsGenerator.sln -bl:msbuild.binlog

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: GermanToCSharpKeywordsGenerator.Unittests/TestResults/test_results.trx