on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          2.1.x

    - name: Restore dependencies
      run: dotnet restore GermanToCSharpGenerator.sln

    - name: Build Generator
      run: dotnet build GermanToCSharpGenerator/GermanToCSharpGenerator.csproj --configuration Release

    - name: Build Example
      run: dotnet build GermanToCSharpGenerator.Example/GermanToCSharpGenerator.Example.csproj --configuration Release

    - name: Run Unit Tests
      run: dotnet test GermanToCSharpGenerator.Unittests/GermanToCSharpGenerator.Unittests.csproj --configuration Release --logger "trx;LogFileName=test_results.trx"

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: GermanToCSharpGenerator.Unittests/TestResults/test_results.trx